# Generated by Django 4.1.7 on 2023-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="dependency",
        ),
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dependency", models.ManyToManyField(blank=True, to="TaskApp.task")),
            ],
        ),
    ]
