# Generated by Django 4.1.7 on 2023-03-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0002_remove_task_dependency_dependency"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dependency",
            field=models.ManyToManyField(blank=True, to="TaskApp.task"),
        ),
        migrations.DeleteModel(
            name="Dependency",
        ),
    ]
