# Generated by Django 4.1.7 on 2023-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0003_task_dependency_delete_dependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="dependency",
            field=models.ManyToManyField(
                blank=True, related_name="dependencies", to="TaskApp.task"
            ),
        ),
    ]
