# Generated by Django 4.1.7 on 2023-03-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0004_alter_task_dependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="endDate",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_title",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="task_title"
            ),
        ),
    ]
