# Generated by Django 4.1.7 on 2023-03-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0005_alter_task_enddate_alter_task_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
