# Generated by Django 4.1.7 on 2023-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0007_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Highest", "Highest"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ],
                default="Low",
                max_length=20,
            ),
        ),
    ]
