# Generated by Django 4.1.7 on 2023-03-28 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0008_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="createdDate",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
