# Generated by Django 4.1.7 on 2023-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskApp", "0010_task_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-createdDate"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="createdDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="Image",
            field=models.ImageField(null=True, upload_to="taskImage"),
        ),
    ]
